"""The V7 candidate-family registry.

One record per behavioural family explored in the Luna B discovery phase,
including the ones that were pruned: the multiplicity universe for the later
tournament must be reconstructible from the lineage, not just from the
survivors.

Every record is data, not prose: the JSON registry emitted by
``scripts/v7_discovery_screen.py`` is a direct serialisation of ``FAMILIES``,
and the frozen serious-candidate subset is digested with SHA-256 so a later
independent pass can prove it evaluated what discovery froze.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from typing import Any

REGISTRY_VERSION = "v7-luna-b-candidate-registry-1.0.0"
CANDIDATE_DEFINITION_VERSION = "v7-luna-b-candidates-1.0.0"


@dataclass(frozen=True)
class Family:
    name: str
    working_name: str
    territory: str
    player_question: str
    why_care: str
    unit_of_observation: str
    estimand: str
    required_fields: tuple[str, ...]
    structural_eligibility: str
    opportunity_definition: str
    context_controls: tuple[str, ...]
    confounders: tuple[str, ...]
    directionality: str
    two_sided: bool
    why_players_differ: str
    expected_structural_reach: str
    expected_information_reach: str
    parsed_dependency: str
    role_position_breadth: str
    patch_sensitivity: str
    provider_and_report_cost: str
    story_example: str
    known_failure_mode: str
    # machine fields consumed by the screen
    arm_family: bool
    treated: str | None = None
    control: str | None = None
    support: int = 30
    arm_support: int = 12
    parsed: bool = False
    negative_control: bool = False

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def _f(**kwargs: Any) -> Family:
    return Family(**kwargs)


FAMILIES: tuple[Family, ...] = (
    _f(
        name="post_loss_next_outcome",
        working_name="Post-Loss result rebound",
        territory="response to setbacks",
        player_question="After you lose a game, does your next game in the same session go differently from what your context predicts?",
        why_care="It is the single most discussed idea in Dota self-talk — whether a loss costs you the next game.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player difference in context-adjusted next-match win indicator between a transition that follows a loss and one that follows a win.",
        required_fields=("is_victory", "started_at", "ended_at", "hero_id", "game_mode_native", "game_version_id", "duration_seconds", "is_radiant", "lobby_type_native"),
        structural_eligibility="Product-context rows only; both matches inside one 3 h-gap session.",
        opportunity_definition="Every consecutive pair of product-context matches whose gap is at most the session gap.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("matchmaking regression to the mean", "party stability", "opponent strength", "session position"),
        directionality="Two-sided; neither rebound nor decline is the expected direction.",
        two_sided=True,
        why_players_differ="Emotional regulation and stop/continue discipline plausibly differ between people in a way a win-rate mean does not capture.",
        expected_structural_reach="High — in-session transitions are the most abundant opportunity in the corpus.",
        expected_information_reach="Low: a binary outcome with a true effect of a few points needs hundreds of transitions per arm.",
        parsed_dependency="None.",
        role_position_breadth="All roles; nothing conditions on position.",
        patch_sensitivity="Low; the estimand is a within-player contrast.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"After a loss you win 4 points less often than your own baseline — one of the steeper drops we measure.\"",
        known_failure_mode="Binary outcome carries almost no information per opportunity, so between-player spread is swamped by sampling noise.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="post_loss_requeue_latency",
        working_name="Loss re-queue speed",
        territory="response to setbacks",
        player_question="After a loss, how long until your next recorded game?",
        why_care="Re-queue speed is a decision the player fully controls, and it is the behavioural core of what people call tilt-queuing.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player difference in context-adjusted log gap to the next match after a loss versus after a win.",
        required_fields=("started_at", "ended_at", "is_victory", "hero_id", "game_mode_native", "game_version_id", "duration_seconds"),
        structural_eligibility="Product-context rows; transition inside one session.",
        opportunity_definition="Log seconds between the end of a match and the start of the next in-session match.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("queue times", "party regrouping", "time of day", "post-game screen length differing by result"),
        directionality="Two-sided; faster and slower are both meaningful.",
        two_sided=True,
        why_players_differ="Re-queue latency is a personal habit; some people rage-queue and some walk away, and the corpus can see it.",
        expected_structural_reach="High.",
        expected_information_reach="High: a continuous response with many observations per player.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"You re-queue 22% faster after a loss than after a win — you are a chaser.\"",
        known_failure_mode="Queue-time and party effects are shared across players, so a population-common effect could dominate; the arm factor removes the mean but not heteroskedastic structure.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="post_loss_session_continuation",
        working_name="Stop-or-chase after a loss",
        territory="response to setbacks / session shape",
        player_question="Does a loss make you keep playing, or make you stop for the day?",
        why_care="Whether you end the night on a loss or chase it back is the most consequential session decision a player makes.",
        unit_of_observation="Match with a known continuation status (not the last observed match).",
        estimand="Per-player difference in context-adjusted probability that another match follows within the session, after a loss versus after a win.",
        required_fields=("is_victory", "started_at", "ended_at", "hero_id", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; the final observed match is right-censored and dropped.",
        opportunity_definition="Every product-context match except the last observed one, labelled by whether another match followed within 3 h.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "hour", "arm"),
        confounders=("time of day", "real-life schedule", "session length already accumulated", "right-censoring at the window edge"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Quit discipline is close to a personality trait and is not implied by skill.",
        expected_structural_reach="High.",
        expected_information_reach="Medium: binary, but with several hundred opportunities per player.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"A loss makes you 11 points more likely to queue again — you almost never end a night on a defeat.\"",
        known_failure_mode="Session boundary is a 3 h modelling choice; the estimand is partly a definition artefact and must be shown stable across gap thresholds before shipping.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="post_loss_hero_switch",
        working_name="Comfort-pick retreat",
        territory="response to setbacks / hero behaviour",
        player_question="After a loss, do you change hero or run it back?",
        why_care="Changing or keeping the hero after a loss is a visible, deliberate choice players recognise in themselves.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player difference in context-adjusted probability the next hero differs, after a loss versus after a win.",
        required_fields=("hero_id", "is_victory", "started_at", "ended_at", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; transition inside one session.",
        opportunity_definition="Indicator that the next in-session match uses a different hero.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("hero pool size", "mode (Turbo encourages experimentation)", "party role assignment", "single-draft and random-draft modes remove the choice"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Some players retreat to a comfort hero after a loss and some abandon the hero that lost; both are stable dispositions.",
        expected_structural_reach="High.",
        expected_information_reach="Medium.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Medium — hero pools shift with patches.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"After a loss you switch hero 9 points more often than after a win.\"",
        known_failure_mode="Single-draft and random-draft matches make the hero non-chosen; they are a small share but must be excluded or modelled before shipping.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="post_loss_mode_switch",
        working_name="Turbo escape hatch",
        territory="response to setbacks / mode mix",
        player_question="When a game goes badly, do you drop down to Turbo?",
        why_care="Switching modes after a loss is a recognisable coping move and is invisible on any normal stats page.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player difference in context-adjusted probability the next match changes mode stratum, after a loss versus after a win.",
        required_fields=("game_mode_native", "is_victory", "started_at", "ended_at", "hero_id", "game_version_id"),
        structural_eligibility="Product-context rows; transition inside one session.",
        opportunity_definition="Indicator that the next in-session match's mode stratum differs.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("players who only ever play one mode have no opportunity", "party mode choice", "time of night"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Mode mix is a taste; whether a setback moves it is a distinct disposition.",
        expected_structural_reach="Medium — a single-mode player contributes no variation, and single-mode players are common.",
        expected_information_reach="Low to medium; the switch rate is low for most players.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Two losses in and you are in Turbo — you switch modes after a loss twice as often as after a win.\"",
        known_failure_mode="Degenerate for single-mode players: reach is structurally bounded by mode mix, which is itself a strong player trait, so the family risks measuring mode mix rather than response.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="post_loss_risk_shift",
        working_name="Post-loss risk shift",
        territory="response to setbacks / risk profile",
        player_question="After you lose, does your next game get more reckless?",
        why_care="\"I threw the next one\" is the folk theory; death exposure is the observable part of it.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player difference in context-adjusted deaths per ten minutes in the next match, after a loss versus after a win.",
        required_fields=("deaths", "duration_seconds", "is_victory", "started_at", "ended_at", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows; transition inside one session.",
        opportunity_definition="Deaths per ten minutes of the following in-session match.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("hero and position change between matches", "match length", "team strength", "deaths are partly a team outcome"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Tilt expression differs: some players get passive after a loss, some get reckless.",
        expected_structural_reach="High.",
        expected_information_reach="Medium-high — a continuous response.",
        parsed_dependency="None; own death *timings* are absent from the corpus but the death count is a history field.",
        role_position_breadth="All roles, but death rate is strongly position-linked, so position drift between matches is a real confounder.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your death rate climbs 12% in the game after a loss.\"",
        known_failure_mode="Deaths per minute is close to a role signal; without position control (parsed-only) the contrast may be picking up post-loss position change rather than risk.",
        arm_family=True, treated="loss", control="win", support=60, arm_support=25,
    ),
    _f(
        name="session_drift_outcome",
        working_name="Session Drift (result)",
        territory="within-session adaptation",
        player_question="Do you get better or worse as a session goes on?",
        why_care="Everyone believes something about their own stamina; almost nobody has evidence.",
        unit_of_observation="Match inside a session of at least four matches.",
        estimand="Per-player difference in context-adjusted win indicator between the late half and the early half of a session.",
        required_fields=("is_victory", "started_at", "ended_at", "hero_id", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; sessions of length four or more; middle match dropped when the length is odd.",
        opportunity_definition="Each match labelled early or late within its own session.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("sessions end because of losses, so late-half membership is outcome-dependent", "time of day", "session length"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Stamina, tilt accumulation, and warm-up curves plausibly differ.",
        expected_structural_reach="Medium-high — needs long sessions.",
        expected_information_reach="Low: binary outcome, few long sessions per player.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your win rate in the back half of a session is 5 points below the front half.\"",
        known_failure_mode="Length-biased sampling: a session continues *because* it is going well, so the early/late contrast is endogenous to the outcome being measured.",
        arm_family=True, treated="late", control="early", support=40, arm_support=20,
    ),
    _f(
        name="session_drift_activity",
        working_name="Session Drift (involvement)",
        territory="within-session adaptation",
        player_question="Do you stay as involved in fights late in a session as you were at the start?",
        why_care="An involvement fade is something a player can actually act on: it says stop after four, not after seven.",
        unit_of_observation="Match inside a session of at least four matches.",
        estimand="Per-player difference in context-adjusted kill-plus-assist involvement per ten minutes, late half versus early half.",
        required_fields=("kills", "assists", "duration_seconds", "started_at", "ended_at", "hero_id", "game_mode_native"),
        structural_eligibility="As above.",
        opportunity_definition="Involvement per ten minutes for each match, labelled early or late.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("same length-biased session sampling", "hero and position drift within a session", "team kill volume"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Fatigue expression is individual and shows up in a continuous quantity long before it shows up in win rate.",
        expected_structural_reach="Medium-high.",
        expected_information_reach="Medium-high — continuous, many matches per player.",
        parsed_dependency="None.",
        role_position_breadth="All roles; involvement level differs strongly by role so the role mix within a session matters.",
        patch_sensitivity="Medium — kill volume per game is patch-sensitive, but the estimand is a within-session contrast.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your fight involvement drops 8% in the back half of long sessions.\"",
        known_failure_mode="Kill-plus-assist per minute is partly a team-tempo quantity; a player who switches to support late in a session will look like a fader.",
        arm_family=True, treated="late", control="early", support=40, arm_support=20,
    ),
    _f(
        name="session_drift_risk",
        working_name="Session Drift (risk)",
        territory="within-session adaptation",
        player_question="Do you die more as a session wears on?",
        why_care="It is the most legible fatigue signal in the game.",
        unit_of_observation="Match inside a session of at least four matches.",
        estimand="Per-player difference in context-adjusted deaths per ten minutes, late half versus early half.",
        required_fields=("deaths", "duration_seconds", "started_at", "ended_at", "hero_id", "game_mode_native"),
        structural_eligibility="As above.",
        opportunity_definition="Deaths per ten minutes for each match, labelled early or late.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("length-biased session sampling", "position drift", "game length"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Concentration decay differs between people.",
        expected_structural_reach="Medium-high.",
        expected_information_reach="Medium-high.",
        parsed_dependency="None.",
        role_position_breadth="All roles; strongly position-linked level.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"You die 15% more often in the back half of a session.\"",
        known_failure_mode="Highly redundant with session_drift_activity; the portfolio can carry at most one session-drift response variable.",
        arm_family=True, treated="late", control="early", support=40, arm_support=20,
    ),
    _f(
        name="warmup_first_match",
        working_name="Warm-up cost",
        territory="within-session adaptation",
        player_question="Do you need a warm-up game before you play like yourself?",
        why_care="It is directly actionable and distinct from a gradual fade: it is a level shift at the first game only.",
        unit_of_observation="Match inside a session of at least three matches.",
        estimand="Per-player difference in context-adjusted involvement per ten minutes between the first match of a session and the rest.",
        required_fields=("kills", "assists", "duration_seconds", "started_at", "ended_at", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows; sessions of length three or more.",
        opportunity_definition="Each match labelled first-of-session or later.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("first match of a session is disproportionately a solo queue", "time of day", "session-length selection"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Some people arrive ready and some need a game; this is a claim about the shape, not the level.",
        expected_structural_reach="High.",
        expected_information_reach="Medium-high — the control arm is large.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your first game of the night runs 9% below the rest — you are a slow starter.\"",
        known_failure_mode="Overlaps session_drift_activity mechanically; the two must be shown to separate before both are carried.",
        arm_family=True, treated="first", control="later", support=40, arm_support=15,
    ),
    _f(
        name="layoff_return",
        working_name="Return from a break",
        territory="cross-match behavioural drift",
        player_question="How do you play the first game back after a few days away?",
        why_care="Players constantly wonder whether time off helps or hurts; here it is measurable.",
        unit_of_observation="Match preceded either by an in-session gap or by a gap of at least three days.",
        estimand="Per-player difference in context-adjusted involvement per ten minutes, returning match versus steady-state match.",
        required_fields=("kills", "assists", "duration_seconds", "started_at", "ended_at", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows; gaps between 3 h and 3 days are dropped so the arms are clean.",
        opportunity_definition="Involvement per ten minutes labelled return or steady.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("patch changes across a long break", "hero pool refresh", "seasonality", "returning players often pick Turbo"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Rust versus refreshment is genuinely individual.",
        expected_structural_reach="Medium — a heavy daily player has few three-day breaks.",
        expected_information_reach="Low: the treated arm is small for exactly the most active players.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="High — long breaks straddle patches by construction.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your first game back after a break is 11% quieter than usual.\"",
        known_failure_mode="Treated-arm scarcity is anti-correlated with the population we can serve; and the patch confound is structural, not incidental.",
        arm_family=True, treated="return", control="steady", support=40, arm_support=12,
    ),
    _f(
        name="requeue_tempo",
        working_name="Queue tempo",
        territory="scheduling and session shape",
        player_question="How fast do you start the next game once one ends?",
        why_care="It is a clean, self-recognisable rhythm, and it frames the post-loss family.",
        unit_of_observation="Adjacent in-session match transition.",
        estimand="Per-player mean context-adjusted log gap between matches.",
        required_fields=("started_at", "ended_at", "hero_id", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; in-session transitions.",
        opportunity_definition="Log seconds between one match ending and the next starting.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "hour"),
        confounders=("queue time by region and time of day", "party regrouping", "no region field exists in the corpus"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Queue rhythm is a habit, though part of it is server-side.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"You are back in queue within 90 seconds — faster than almost anyone we look at.\"",
        known_failure_mode="A level family with no contrast is a population-position statement dressed as a Finding; it also partly measures the player's region and hardware, not the player.",
        arm_family=False, support=100,
    ),
    _f(
        name="session_length",
        working_name="Session length habit",
        territory="scheduling and session shape",
        player_question="How long do your sessions run once you sit down?",
        why_care="It frames every other session claim.",
        unit_of_observation="Session.",
        estimand="Per-player mean context-adjusted log session length in matches.",
        required_fields=("started_at", "ended_at", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; every session including single-match sessions.",
        opportunity_definition="Log number of matches in the session.",
        context_controls=("hour", "weekday", "mode", "patch"),
        confounders=("real-life schedule", "session-gap definition", "window truncation for nine flagged accounts"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="It varies enormously — but it is lifestyle, not gameplay identity.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your median session is five games long.\"",
        known_failure_mode="This is a descriptive fact about someone's calendar, not a behavioural response; it belongs in reference context, not in a Finding.",
        arm_family=False, support=30,
    ),
    _f(
        name="offpeak_shift",
        working_name="Off-peak hours shift",
        territory="scheduling / timing consistency",
        player_question="Do you play differently in your own off-hours?",
        why_care="\"Never queue at 2 a.m.\" is advice a player can use — if it is true for them.",
        unit_of_observation="Product-context match.",
        estimand="Per-player difference in context-adjusted involvement per ten minutes between the player's own off-peak four-hour block and the rest.",
        required_fields=("kills", "assists", "duration_seconds", "started_at", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows; players with at least 24 matches so the peak block is identifiable.",
        opportunity_definition="Every match labelled by whether its UTC hour falls in the player's own off-peak block.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("no timezone or region field exists, so the block is defined relative to the player's own modal hour", "off-peak matches are disproportionately Turbo", "off-peak play may be a different party"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Chronotype and discipline differ.",
        expected_structural_reach="Medium-high.",
        expected_information_reach="Low: the off-peak arm is by construction the player's thinnest block.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your late-block games run 14% quieter than your prime-time games.\"",
        known_failure_mode="Defining off-peak as the block opposite the peak is arbitrary; the treated arm is smallest exactly where it needs to be largest.",
        arm_family=True, treated="offpeak", control="peak", support=60, arm_support=15,
    ),
    _f(
        name="weekend_shift",
        working_name="Weekend versus weekday",
        territory="scheduling",
        player_question="Are your weekend games a different kind of game?",
        why_care="Low: it is a calendar fact more than a behavioural one.",
        unit_of_observation="Product-context match.",
        estimand="Per-player difference in context-adjusted involvement per ten minutes, weekend versus weekday.",
        required_fields=("kills", "assists", "duration_seconds", "started_at", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows.",
        opportunity_definition="Every match labelled weekend or weekday in UTC.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("no timezone field, so the weekend boundary is UTC and wrong for many players", "party composition"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Weakly; most players' weekend games are the same games.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your weekend games look identical to your weekday games.\"",
        known_failure_mode="UTC weekend boundaries are wrong without a timezone; and the effect is expected to be near-zero for nearly everyone, which is not identity.",
        arm_family=True, treated="weekend", control="weekday", support=60, arm_support=25,
    ),
    _f(
        name="hero_novelty",
        working_name="Novelty appetite",
        territory="hero and pool behaviour",
        player_question="Do you keep reaching for heroes you have not touched in a month?",
        why_care="Explorer versus loyalist is a real identity axis and it is not a skill claim.",
        unit_of_observation="Product-context match after a 30-match warm-up.",
        estimand="Per-player mean context-adjusted rate of playing a hero unseen in the previous 30 days.",
        required_fields=("hero_id", "started_at", "game_mode_native", "game_version_id", "lobby_type_native"),
        structural_eligibility="Product-context rows; first 30 matches used only to build history.",
        opportunity_definition="Indicator that the hero was not played in the previous 30 days.",
        context_controls=("mode", "patch", "lobby"),
        confounders=("total match volume mechanically lowers novelty rate", "random and single draft force novelty", "new heroes released in a patch"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Hero-pool breadth is one of the most individual things about a Dota player.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Medium — patch releases create novelty for everyone at once.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"One game in nine is a hero you have not touched in a month.\"",
        known_failure_mode="Mechanically anti-correlated with match volume, so it partly measures how much someone plays; the rate must be volume-adjusted before shipping.",
        arm_family=False, support=100,
    ),
    _f(
        name="transfer_outcome",
        working_name="Transfer (result)",
        territory="hero and pool behaviour",
        player_question="How much does your result depend on being on a comfort hero?",
        why_care="\"What survives when the hero changes\" is the V6 Transfer question and players ask it constantly.",
        unit_of_observation="Product-context match after a 50-match warm-up.",
        estimand="Per-player difference in context-adjusted win indicator between comfort-pool heroes and heroes outside it, where the pool is built from strictly prior matches.",
        required_fields=("hero_id", "is_victory", "started_at", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; comfort pool is the five most-played heroes to date.",
        opportunity_definition="Each match labelled comfort or stretch by the causal pool.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("hero strength differs between pool and non-pool heroes", "position changes with hero", "the pool is chosen, so selection is endogenous"),
        directionality="Two-sided; a small gap is the interesting direction.",
        two_sided=True,
        why_players_differ="Some players are their heroes and some are not.",
        expected_structural_reach="High.",
        expected_information_reach="Low: a binary outcome contrast.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Off your top five you win only two points less often — your game travels.\"",
        known_failure_mode="Hero fixed effects are in the context projection, which absorbs much of the very contrast being estimated; and a binary outcome cannot carry a two-point effect at these sample sizes.",
        arm_family=True, treated="stretch", control="comfort", support=60, arm_support=25,
    ),
    _f(
        name="transfer_activity",
        working_name="Transfer (involvement)",
        territory="hero and pool behaviour",
        player_question="Does your fight involvement hold up on a hero you barely play?",
        why_care="It says whether your playstyle is portable or hero-shaped — a genuinely identity-like claim.",
        unit_of_observation="Product-context match after a 50-match warm-up.",
        estimand="Per-player difference in context-adjusted involvement per ten minutes, stretch heroes versus comfort-pool heroes.",
        required_fields=("hero_id", "kills", "assists", "duration_seconds", "started_at", "game_mode_native"),
        structural_eligibility="As above.",
        opportunity_definition="Involvement per ten minutes labelled comfort or stretch.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("hero-intrinsic involvement level", "position change with hero", "stretch heroes are played in different modes"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Playstyle portability is a real and personal thing.",
        expected_structural_reach="High.",
        expected_information_reach="Medium-high — continuous response.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"On unfamiliar heroes your involvement barely moves — you bring the same game.\"",
        known_failure_mode="Hero is a context factor, so the projection removes hero-intrinsic involvement; whatever is left may be tiny, and if hero is dropped from the controls the estimand becomes a hero-strength effect.",
        arm_family=True, treated="stretch", control="comfort", support=60, arm_support=25,
    ),
    _f(
        name="transfer_risk",
        working_name="Transfer (risk)",
        territory="hero and pool behaviour",
        player_question="Do you die more when you step off your comfort heroes?",
        why_care="It quantifies the real cost of experimenting.",
        unit_of_observation="Product-context match after a 50-match warm-up.",
        estimand="Per-player difference in context-adjusted deaths per ten minutes, stretch versus comfort.",
        required_fields=("hero_id", "deaths", "duration_seconds", "started_at", "game_mode_native"),
        structural_eligibility="As above.",
        opportunity_definition="Deaths per ten minutes labelled comfort or stretch.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "arm"),
        confounders=("same as transfer_activity", "death rate is strongly hero- and position-linked"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Risk calibration on unfamiliar heroes differs.",
        expected_structural_reach="High.",
        expected_information_reach="Medium-high.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Off your comfort heroes you die 18% more — experimenting costs you.\"",
        known_failure_mode="Same hero-absorption problem as the other Transfer variants; also highly redundant with them.",
        arm_family=True, treated="stretch", control="comfort", support=60, arm_support=25,
    ),
    _f(
        name="risk_appetite",
        working_name="Risk appetite level",
        territory="risk and tempo profile",
        player_question="Relative to your own context, do you play on the front foot or hold back?",
        why_care="A two-sided tempo axis players recognise instantly.",
        unit_of_observation="Product-context match.",
        estimand="Per-player mean context-adjusted deaths per ten minutes.",
        required_fields=("deaths", "duration_seconds", "hero_id", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows.",
        opportunity_definition="Deaths per ten minutes.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby"),
        confounders=("position mix is not controlled without parsed data", "team quality", "hero"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Risk tolerance is a core play-style axis.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None; adding position control makes it parsed-dependent.",
        role_position_breadth="All roles but strongly position-driven, and position mix is itself behaviour.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"You die a third more often than your heroes and modes would predict — you play forward.\"",
        known_failure_mode="Without position control this is largely a position-mix statistic, and a level family invites a good/bad reading; it is closer to a percentile than a Finding.",
        arm_family=False, support=100,
    ),
    _f(
        name="involvement_level",
        working_name="Involvement level",
        territory="fight participation",
        player_question="Are you in more fights than your heroes and modes predict?",
        why_care="Moderate — but it sits very close to raw performance.",
        unit_of_observation="Product-context match.",
        estimand="Per-player mean context-adjusted kill-plus-assist involvement per ten minutes.",
        required_fields=("kills", "assists", "duration_seconds", "hero_id", "game_mode_native"),
        structural_eligibility="Product-context rows.",
        opportunity_definition="Involvement per ten minutes.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby"),
        confounders=("team kill volume", "position mix", "skill"),
        directionality="Two-sided in principle, one-sided in perception.",
        two_sided=False,
        why_players_differ="Because they play different positions and at different skill levels — which is the problem.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your involvement runs above what your heroes predict.\"",
        known_failure_mode="This is KDA dressed as identity and reads as a skill percentile; carried only as a redundancy reference for the other involvement families.",
        arm_family=False, support=100,
    ),
    _f(
        name="side_sensitivity",
        working_name="Radiant/Dire sensitivity (negative control)",
        territory="declared null",
        player_question="Do you play better on one side of the map?",
        why_care="They should not, and that is the point: this family exists to calibrate the screen.",
        unit_of_observation="Product-context match.",
        estimand="Per-player difference in context-adjusted win indicator, Radiant versus Dire.",
        required_fields=("is_radiant", "is_victory", "hero_id", "game_mode_native", "game_version_id"),
        structural_eligibility="Product-context rows; side is excluded from the context controls so it can be the arm.",
        opportunity_definition="Every match labelled by side.",
        context_controls=("mode", "patch", "hero", "duration", "lobby", "arm"),
        confounders=("none material; side assignment is matchmaker-controlled",),
        directionality="Expected null.",
        two_sided=True,
        why_players_differ="They should not, beyond sampling noise.",
        expected_structural_reach="High.",
        expected_information_reach="High opportunity count, near-zero true signal.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="Low.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="Not a shippable Finding.",
        known_failure_mode="If this family shows apparent heterogeneity, the screen's variance decomposition is optimistic and every other number in the table needs discounting.",
        arm_family=True, treated="R", control="D", support=60, arm_support=25, negative_control=True,
    ),
    _f(
        name="duration_tempo",
        working_name="Game-length tempo",
        territory="risk and tempo profile",
        player_question="Do your games end faster than comparable games?",
        why_care="Weak — game length is a ten-player outcome.",
        unit_of_observation="Product-context match.",
        estimand="Per-player mean context-adjusted log match duration.",
        required_fields=("duration_seconds", "hero_id", "game_mode_native", "game_version_id", "is_victory"),
        structural_eligibility="Product-context rows.",
        opportunity_definition="Log duration, controlling for result so that the estimand is not a win-rate restatement.",
        context_controls=("mode", "patch", "hero", "lobby", "result"),
        confounders=("nine other players", "matchmaking", "mode"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Mostly they do not; one player has limited leverage on game length.",
        expected_structural_reach="High.",
        expected_information_reach="High.",
        parsed_dependency="None.",
        role_position_breadth="All roles.",
        patch_sensitivity="High — game length is one of the most patch-sensitive quantities in Dota.",
        provider_and_report_cost="History only. Trivial compute.",
        story_example="\"Your games run four minutes shorter than comparable games.\"",
        known_failure_mode="A ten-player outcome attributed to one player; also the most patch-driven quantity available.",
        arm_family=False, support=100,
    ),
    _f(
        name="fight_timing_centroid",
        working_name="Fight-timing centre of gravity",
        territory="fight participation timing",
        player_question="Is your impact concentrated early or late in a game?",
        why_care="Early-game player versus late-game player is a genuine identity, and Turbo/standard pooling only works because the scale is normalised game progress.",
        unit_of_observation="Parsed product-context match with at least three own fight events.",
        estimand="Per-player mean context-adjusted normalised-progress centroid of own kill and assist event times.",
        required_fields=("stats.kill_events.time", "stats.assist_events.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="Parsed rows joined to a product-context history row; parsed detail present.",
        opportunity_definition="Mean of own event times divided by match duration.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane"),
        confounders=("hero power curve", "position", "match length", "team tempo"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Timing preference is a strong, stable style axis.",
        expected_structural_reach="Product-wide high; research reach limited to the 116 DISCOVERY parsed accounts.",
        expected_information_reach="High — a bounded continuous quantity with many events per match.",
        parsed_dependency="Full: parsed event timings and role context.",
        role_position_breadth="All five positions; the level differs sharply by position so position control is essential.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"Your fights cluster in the first third of the game — you are an early-tempo player.\"",
        known_failure_mode="Assist timings enter the shape; if the assist stream is systematically incomplete for some matches the centroid is biased, and the corpus tells us the assist *count* is unreliable.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="first_fight_timing",
        working_name="Time to first fight",
        territory="fight participation timing",
        player_question="How early do you get involved?",
        why_care="A crisp, single-number habit.",
        unit_of_observation="Parsed product-context match with at least one own fight event.",
        estimand="Per-player mean context-adjusted normalised progress of the first own kill or assist event.",
        required_fields=("stats.kill_events.time", "stats.assist_events.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="As above.",
        opportunity_definition="Earliest own event time divided by duration.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane"),
        confounders=("first-blood luck", "lane matchup", "position"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Early aggression is individual.",
        expected_structural_reach="Same parsed denominators.",
        expected_information_reach="Medium — a first-order statistic is noisier than a centroid.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"Your first fight lands at 11% of game time — earlier than almost anyone.\"",
        known_failure_mode="Strongly redundant with the centroid, and a minimum statistic is dominated by a single lucky event.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="state_responsive_participation",
        working_name="Game-state responsiveness",
        territory="game-state responsiveness",
        player_question="When your team falls behind, do you fight more or go quiet?",
        why_care="This is the closest thing the corpus offers to a mental-game Finding that is not a moral judgement: it is a two-sided style claim about how you respond to a losing position.",
        unit_of_observation="Parsed product-context match containing at least three clearly-behind and three clearly-ahead minutes.",
        estimand="Per-player difference in context-adjusted own fight events per minute of state, behind versus ahead, where behind and ahead are own-team net-worth lead beyond ±5,000 gold.",
        required_fields=("radiant_networth_leads", "is_radiant", "stats.kill_events.time", "stats.assist_events.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="Parsed rows joined to a product-context history row; both states must occur in the same match, which makes the contrast within-match.",
        opportunity_definition="Two rows per qualifying match: events per behind-minute and events per ahead-minute.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("games that swing are systematically different games", "fights happen more when behind because the enemy is pushing", "team behaviour drives own events", "the ±5,000 threshold means different things in Turbo"),
        directionality="Two-sided; both fighting on and fading are real styles.",
        two_sided=True,
        why_players_differ="Response to a losing position is a plausible and player-facing disposition, not a skill level.",
        expected_structural_reach="Bounded by the parsed subset; within it, most matches that swing qualify.",
        expected_information_reach="Medium-high — continuous, two rows per match.",
        parsed_dependency="Full: net-worth trajectory plus own event timings.",
        role_position_breadth="All five positions; supports fight less in both states, so position control matters.",
        patch_sensitivity="Medium; the gold threshold is patch- and mode-sensitive and should be expressed on a mode-relative scale before shipping.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"When your team is 5k down you fight *more*, not less — you are a player who tries to swing it back.\"",
        known_failure_mode="The fixed ±5,000 gold cut is a wall-clock-like choice on a Turbo/standard-pooled sample; a mode-relative or progress-relative threshold is the correct final form and this discovery version has not yet made that change.",
        arm_family=True, treated="behind", control="ahead", support=40, arm_support=15, parsed=True,
    ),
    _f(
        name="state_responsive_participation_minutes",
        working_name="Game-state responsiveness (minute sampling variant)",
        territory="game-state responsiveness",
        player_question="When your team falls behind, do you fight more or go quiet?",
        why_care="Same behavioural question as state_responsive_participation; recorded separately because it is a materially different sampling model rather than a cosmetic change.",
        unit_of_observation="One clearly-behind or clearly-ahead minute of a parsed product-context match.",
        estimand="Per-player difference in context-adjusted own fight events per state minute, behind versus ahead.",
        required_fields=("radiant_networth_leads", "is_radiant", "stats.kill_events.time", "stats.assist_events.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="Identical to state_responsive_participation.",
        opportunity_definition="One row per state minute rather than one row per match-arm, so the player's arm mean becomes a ratio of sums instead of a mean of small-denominator ratios.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("identical to state_responsive_participation", "minutes within a match are strongly dependent, so nominal opportunity counts overstate information"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Identical to state_responsive_participation.",
        expected_structural_reach="Identical to state_responsive_participation.",
        expected_information_reach="Nominally much higher, but minute-level dependence means the effective information is far below the raw count.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="Same story as state_responsive_participation.",
        known_failure_mode="Within-match minute dependence inflates apparent precision; only one of the two sampling variants may enter the portfolio.",
        arm_family=True, treated="behind", control="ahead", support=200, arm_support=80, parsed=True,
    ),
    _f(
        name="state_responsive_purchasing",
        working_name="Build tempo under pressure",
        territory="item timing and build adaptation",
        player_question="When you are behind, do you keep farming and buying, or does your economy stall?",
        why_care="It separates players who keep a game going from players whose game collapses with the scoreline — and it never needs to know what the item was.",
        unit_of_observation="Parsed product-context match with at least three behind and three ahead minutes.",
        estimand="Per-player difference in context-adjusted item purchases per minute of state, behind versus ahead.",
        required_fields=("radiant_networth_leads", "is_radiant", "stats.item_purchases.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="As above.",
        opportunity_definition="Two rows per qualifying match: purchases per behind-minute and per ahead-minute.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("purchase count includes consumables, so it is partly a support/core signal", "being behind mechanically reduces gold", "item identity and tiering are unverified in this corpus"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Economic discipline under pressure is individual, and it is invisible on any scoreboard.",
        expected_structural_reach="Parsed subset only.",
        expected_information_reach="High — purchases are frequent, median 25 per match.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions; supports buy far more consumables, so position control is essential.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required; 3.75 M purchase events in the corpus. Moderate compute.",
        story_example="\"Behind by 5k your buying rate barely drops — your economy does not tilt.\"",
        known_failure_mode="Being behind causally reduces gold income, so a population-wide drop is guaranteed; only the *between-player* deviation from that population effect is a Finding, and the estimand must be read that way.",
        arm_family=True, treated="behind", control="ahead", support=40, arm_support=15, parsed=True,
    ),
    _f(
        name="kill_share",
        working_name="Kill share of team",
        territory="fight participation structure",
        player_question="What share of your team's kills do you take yourself?",
        why_care="It separates finishers from enablers without calling either one better.",
        unit_of_observation="Parsed product-context match with at least eight own-team kills.",
        estimand="Per-player mean context-adjusted ratio of own kill events to own-team kills.",
        required_fields=("stats.kill_events", "radiant_kills", "dire_kills", "is_radiant", "position_native", "role_native", "lane_native"),
        structural_eligibility="Parsed rows joined to product context; own-team kill total at least eight.",
        opportunity_definition="Own kill-event count divided by own-team kill total. Assist events are excluded on purpose: their count disagrees with the history table in 48% of rows.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("position determines this almost entirely", "hero", "team composition"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Largely because they play different positions — which is the risk.",
        expected_structural_reach="Parsed subset.",
        expected_information_reach="High.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions but overwhelmingly position-determined.",
        patch_sensitivity="Low.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"You take a third of your team's kills from position four — unusual for the role.\"",
        known_failure_mode="After position control there may be little left; before it, the family is a role restatement.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="purchase_tempo",
        working_name="Build tempo landmark",
        territory="item timing",
        player_question="How far into a game are you when you make your eighth purchase?",
        why_care="Build pace is a real rhythm, and normalised progress makes it comparable across Turbo and standard.",
        unit_of_observation="Parsed product-context match with at least eight purchases.",
        estimand="Per-player mean context-adjusted normalised progress at the eighth item purchase.",
        required_fields=("stats.item_purchases.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="As above.",
        opportunity_definition="Progress at the eighth purchase event.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane"),
        confounders=("consumables inflate early counts", "item identity unverified", "supports buy differently", "game length"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Farming rhythm is individual.",
        expected_structural_reach="Parsed subset.",
        expected_information_reach="High.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions.",
        patch_sensitivity="Medium — item costs move with patches.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"Your eighth item lands at 30% of game time.\"",
        known_failure_mode="The eighth purchase is an arbitrary landmark over an unverified item vocabulary, so it mixes consumables and real items; the atlas rates item semantics MEDIUM and unverified.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="lane_recovery_participation",
        working_name="Lane Recovery (participation)",
        territory="response to setbacks / lane",
        player_question="When your lane loses, do you still show up in the second half of the game?",
        why_care="Recovering from a bad lane is the most common thing a Dota player has to do.",
        unit_of_observation="Parsed product-context match with a decided lane outcome for the player's own lane.",
        estimand="Per-player difference in context-adjusted own fight events per ten minutes of the second half of game progress, lost lane versus won lane.",
        required_fields=("top/mid/bottom_lane_outcome_native", "lane_native", "is_radiant", "stats.kill_events.time", "stats.assist_events.time", "duration_seconds"),
        structural_eligibility="Parsed rows joined to product context; lane must be SAFE/OFF/MID and the lane outcome must not be TIE.",
        opportunity_definition="Own event count in the second half of game progress, scaled to a ten-minute rate.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("the lane outcome is a *team-level* verdict on that lane, not the player's own", "roamers and junglers have no lane", "ties are dropped, which is a third of lanes"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Resilience after a bad start is plausibly individual.",
        expected_structural_reach="Parsed subset, further reduced by TIE lanes and missing lane assignment.",
        expected_information_reach="Medium.",
        parsed_dependency="Full, plus lane-outcome semantics rated MEDIUM in the atlas.",
        role_position_breadth="Three lanes only; jungle and roaming are too sparse to carry it.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"Even when your lane loses, your second-half presence holds — you do not fold.\"",
        known_failure_mode="The trigger is a team-level lane verdict, so a player can be assigned a lost lane they personally won; this attribution error is not recoverable from this corpus.",
        arm_family=True, treated="lost", control="won", support=40, arm_support=15, parsed=True,
    ),
    _f(
        name="lane_recovery_outcome",
        working_name="Lane Recovery (result)",
        territory="response to setbacks / lane",
        player_question="How much does a lost lane cost you in the end?",
        why_care="It is the version of the question players actually ask.",
        unit_of_observation="Parsed product-context match with a decided own-lane outcome.",
        estimand="Per-player difference in context-adjusted win indicator, lost lane versus won lane.",
        required_fields=("top/mid/bottom_lane_outcome_native", "lane_native", "is_radiant", "is_victory"),
        structural_eligibility="As above.",
        opportunity_definition="Win indicator labelled by own-lane outcome.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("a lost lane is a lost lane for the whole team", "same team-level attribution problem", "binary outcome"),
        directionality="Two-sided; a small gap is the interesting direction.",
        two_sided=True,
        why_players_differ="Weakly: the lane outcome largely determines the game for everyone.",
        expected_structural_reach="Parsed subset minus ties.",
        expected_information_reach="Low: binary response on a reduced sample.",
        parsed_dependency="Full.",
        role_position_breadth="Three lanes only.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"A lost lane costs you 20 points of win rate — about average.\"",
        known_failure_mode="Almost no player-level heterogeneity is plausible: losing your lane is bad for everyone by roughly the same amount.",
        arm_family=True, treated="lost", control="won", support=40, arm_support=15, parsed=True,
    ),
    _f(
        name="lead_retention",
        working_name="Lead conversion",
        territory="lead conversion and retention",
        player_question="When your team is clearly ahead at the midpoint, do your games close out?",
        why_care="Throwing leads is the most emotionally loaded pattern in Dota.",
        unit_of_observation="Parsed product-context match whose midpoint net-worth lead exceeds ±5,000 gold.",
        estimand="Per-player difference in context-adjusted win indicator between decided-ahead and decided-behind midpoints.",
        required_fields=("radiant_networth_leads", "is_radiant", "is_victory", "duration_seconds"),
        structural_eligibility="Parsed rows joined to product context; trajectory of at least eight minutes.",
        opportunity_definition="Win indicator labelled by the sign of the midpoint lead.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane", "arm"),
        confounders=("the trajectory is a team quantity shared with four teammates", "matchmaking", "duration is post-treatment"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Barely: one of five players has limited leverage on whether a 5k lead converts.",
        expected_structural_reach="Parsed subset.",
        expected_information_reach="Low: binary and heavily saturated — most decided leads convert.",
        parsed_dependency="Full.",
        role_position_breadth="All positions.",
        patch_sensitivity="High — comeback mechanics are a patch lever.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"You convert 5k leads at 88% — the usual rate.\"",
        known_failure_mode="A team outcome attributed to one player, with a saturated binary response; expected to show near-zero player heterogeneity, which is exactly what learning 9 says to reject.",
        arm_family=True, treated="ahead", control="behind", support=40, arm_support=15, parsed=True,
    ),
    _f(
        name="comeback_participation",
        working_name="Deficit presence",
        territory="comeback behaviour",
        player_question="Are you more or less present than usual while your team is behind?",
        why_care="It is the deficit half of game-state responsiveness, expressed as a share so it is immune to how long the game was behind.",
        unit_of_observation="Parsed product-context match with at least four own events and both behind and ahead minutes.",
        estimand="Per-player mean context-adjusted difference between the share of own events landing in behind-minutes and the share of the game spent behind.",
        required_fields=("radiant_networth_leads", "is_radiant", "stats.kill_events.time", "stats.assist_events.time"),
        structural_eligibility="Parsed rows joined to product context.",
        opportunity_definition="Event share minus exposure share, so the population baseline is zero by construction.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane"),
        confounders=("fights are denser in losing positions for everyone", "team behaviour", "the sign of the lead is a coarse state"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Presence under pressure is individual.",
        expected_structural_reach="Parsed subset.",
        expected_information_reach="Medium-high.",
        parsed_dependency="Full.",
        role_position_breadth="All positions.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"A third more of your fight involvement happens while behind than the clock alone would give you.\"",
        known_failure_mode="Strongly redundant with state_responsive_participation, which uses a sharper state definition; the portfolio can carry one, not both.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="early_fight_rate",
        working_name="Early-game fight rate",
        territory="fight participation timing",
        player_question="How busy are your first ten minutes?",
        why_care="Early tempo is a recognisable style.",
        unit_of_observation="Parsed product-context match.",
        estimand="Per-player mean context-adjusted own events per minute in the first quarter of game progress.",
        required_fields=("stats.kill_events.time", "stats.assist_events.time", "duration_seconds", "position_native", "role_native", "lane_native"),
        structural_eligibility="Parsed rows joined to product context.",
        opportunity_definition="Own events at progress ≤ 0.25, per minute of that span.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "position", "role", "lane"),
        confounders=("position", "hero", "team aggression", "lane matchup"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Early aggression is stable and personal.",
        expected_structural_reach="Parsed subset.",
        expected_information_reach="High.",
        parsed_dependency="Full.",
        role_position_breadth="All five positions.",
        patch_sensitivity="Medium.",
        provider_and_report_cost="Parsed detail required. Moderate compute.",
        story_example="\"Your first ten minutes are twice as busy as your position predicts.\"",
        known_failure_mode="Redundant with the fight-timing centroid, and a rate rather than a shape means it leans towards a performance reading.",
        arm_family=False, support=40, parsed=True,
    ),
    _f(
        name="position_flexibility",
        working_name="Position flexibility",
        territory="mode and position mix behaviour",
        player_question="Do you play the same position game after game, or rotate?",
        why_care="The median account has played all five positions, so position mix is behaviour rather than an attribute — and flexibility is a real identity.",
        unit_of_observation="Consecutive in-session parsed match pair.",
        estimand="Per-player mean context-adjusted probability that the position changes between consecutive in-session matches.",
        required_fields=("position_native", "started_at", "ended_at"),
        structural_eligibility="Two consecutive product-context matches, both parsed, inside one session.",
        opportunity_definition="Indicator that the position differs from the previous in-session match.",
        context_controls=("mode", "patch", "hero", "duration", "side", "lobby", "prev_position"),
        confounders=("parsed availability must hold for *both* matches, which compounds the selection", "party role assignment", "role queue behaviour", "hero is in the controls and is nearly collinear with position"),
        directionality="Two-sided.",
        two_sided=True,
        why_players_differ="Some players are one-position players and some fill; this is a strong and legible axis.",
        expected_structural_reach="Parsed subset, further reduced by the consecutive-pair requirement.",
        expected_information_reach="High where it applies.",
        parsed_dependency="Full and doubled: two parsed matches in a row.",
        role_position_breadth="All five positions by construction.",
        patch_sensitivity="Low.",
        provider_and_report_cost="Parsed detail required. Trivial compute.",
        story_example="\"Four games in five you change position — you are the fill player.\"",
        known_failure_mode="Hero is in the context controls and is close to collinear with position, so the projection may absorb most of the signal; and requiring two consecutive parsed matches compounds parsed selection.",
        arm_family=False, support=40, parsed=True,
    ),
)

FAMILY_BY_NAME = {family.name: family for family in FAMILIES}


def registry_payload(names: tuple[str, ...] | None = None) -> dict[str, Any]:
    selected = FAMILIES if names is None else tuple(FAMILY_BY_NAME[name] for name in names)
    return {
        "registry_version": REGISTRY_VERSION,
        "candidate_definition_version": CANDIDATE_DEFINITION_VERSION,
        "families": [family.as_dict() for family in selected],
    }


def canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def digest(payload: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()


__all__ = [
    "CANDIDATE_DEFINITION_VERSION",
    "FAMILIES",
    "FAMILY_BY_NAME",
    "REGISTRY_VERSION",
    "Family",
    "canonical_json",
    "digest",
    "registry_payload",
]
