"""Version identifiers for deterministic Hero Portfolio and action artifacts."""

HERO_PORTFOLIO_VERSION = "hero-portfolio-1.2.0"
HERO_MIRROR_VERSION = "hero-mirror-1.2.0"
HERO_PORTFOLIO_STORY_VERSION = "hero-portfolio-story-1.2.0"
HERO_RELATIONSHIPS_VERSION = "hero-relationships-1.0.0"
HERO_EXPRESSIONS_VERSION = "hero-expressions-1.0.0"
HERO_RELIABILITY_VERSION = "hero-reliability-1.0.0"
HERO_MATCHUPS_VERSION = "hero-matchups-1.0.0"
HERO_SYNERGIES_VERSION = "hero-synergies-1.0.0"
HERO_SITUATIONS_VERSION = "hero-situations-1.0.0"
PATTERN_ACTIONS_VERSION = "pattern-actions-1.0.0"
